### ISSUE TITLE
0.9.28: Segfault upon trying to add plugin

### ISSUE THREAD

**Issue by dvzrv** [rncbc/qtractor#362]
Hi! upon trying to add a plugin to a track, qtractor crashes with a segmentation fault:

```
           PID: 982398 (qtractor)
           UID: 1000 (dave)
           GID: 1000 (dave)
        Signal: 11 (SEGV)
     Timestamp: Sat 2022-09-24 15:32:59 CEST (9min ago)
  Command Line: qtractor
    Executable: /usr/bin/qtractor
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (dave)
       Boot ID: 58b3a533e05145d0bcbf5bf545a97b89
    Machine ID: a5640b7a4f7946aa8d2d075962e96526
      Hostname: hmbx
       Storage: /var/lib/systemd/coredump/core.qtractor.1000.58b3a533e05145d0bcbf5bf545a97b89.982398.1664026379000000.zst (present)
     Disk Size: 6.5M
       Message: Process 982398 (qtractor) of user 1000 dumped core.
```

After adding a track, right clicking on the track, going to properties and trying to "Add" a plugin for the track the application crashes.

This is the stactrace:
```
(gdb)
#0  0x0000001d0d2d4829 in  ()
#1  0x0000001d0d3e4ba0 in  ()
#2  0x0000001d0d2dc85e in  ()
#3  0x000064bf4b2f2253 in  () at /usr/lib/libQt6Core.so.6
#4  0x000064bf4c196897 in QAbstractButton::clicked(bool) () at /usr/lib/libQt6Widgets.so.6
#5  0x000064bf4c18e980 in  () at /usr/lib/libQt6Widgets.so.6
#6  0x000064bf4c18ec71 in  () at /usr/lib/libQt6Widgets.so.6
#7  0x000064bf4c19ad45 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt6Widgets.so.6
#8  0x000064bf4c29adff in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt6Widgets.so.6
#9  0x000064bf4c0da9a5 in QWidget::event(QEvent*) () at /usr/lib/libQt6Widgets.so.6
#10 0x000064bf4c096bcc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#11 0x000064bf4c090509 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#12 0x000064bf4b29f1c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#13 0x000064bf4c08cd69 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/libQt6Widgets.so.6
#14 0x000064bf4c0ef3ae in  () at /usr/lib/libQt6Widgets.so.6
#15 0x000064bf4c0ea525 in  () at /usr/lib/libQt6Widgets.so.6
#16 0x000064bf4c096bcc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#17 0x000064bf4b29f1c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#18 0x000064bf4b89565c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt6Gui.so.6
#19 0x000064bf4b8f3285 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Gui.so.6
#20 0x000064bf4bc7af75 in  () at /usr/lib/libQt6Gui.so.6
#21 0x000064bf4a4c181b in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#22 0x000064bf4a517ec9 in  () at /usr/lib/libglib-2.0.so.0
#23 0x000064bf4a4c00d2 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#24 0x000064bf4b4c1422 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#25 0x000064bf4b2a9b94 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#26 0x000064bf4c2be09b in QDialog::exec() () at /usr/lib/libQt6Widgets.so.6
#27 0x0000001d0d44e7c7 in  ()
#28 0x000064bf4b2f2253 in  () at /usr/lib/libQt6Core.so.6
#29 0x000064bf4bbafbd7 in QAction::triggered(bool) () at /usr/lib/libQt6Gui.so.6
#30 0x000064bf4bbb61c9 in QAction::activate(QAction::ActionEvent) () at /usr/lib/libQt6Gui.so.6
#31 0x000064bf4c2324ab in  () at /usr/lib/libQt6Widgets.so.6
#32 0x000064bf4c237cac in  () at /usr/lib/libQt6Widgets.so.6
#33 0x000064bf4c0da9a5 in QWidget::event(QEvent*) () at /usr/lib/libQt6Widgets.so.6
#34 0x000064bf4c096bcc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#35 0x000064bf4c090509 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#36 0x000064bf4b29f1c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#37 0x000064bf4c08cd69 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/libQt6Widgets.so.6
#38 0x000064bf4c0ef973 in  () at /usr/lib/libQt6Widgets.so.6
#39 0x000064bf4c0ea525 in  () at /usr/lib/libQt6Widgets.so.6
#40 0x000064bf4c096bcc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#41 0x000064bf4b29f1c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#42 0x000064bf4b89565c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt6Gui.so.6
#43 0x000064bf4b8f3285 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Gui.so.6
#44 0x000064bf4bc7af75 in  () at /usr/lib/libQt6Gui.so.6
#45 0x000064bf4a4c181b in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#46 0x000064bf4a517ec9 in  () at /usr/lib/libglib-2.0.so.0
#47 0x000064bf4a4c00d2 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#48 0x000064bf4b4c1422 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#49 0x000064bf4b2a9b94 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#50 0x000064bf4c23c7e8 in  () at /usr/lib/libQt6Widgets.so.6
#51 0x000064bf4c23c903 in QMenu::exec(QPoint const&, QAction*) () at /usr/lib/libQt6Widgets.so.6
#52 0x000064bf4c0daccf in QWidget::event(QEvent*) () at /usr/lib/libQt6Widgets.so.6
#53 0x000064bf4c165dd7 in QFrame::event(QEvent*) () at /usr/lib/libQt6Widgets.so.6
#54 0x000064bf4b29dc18 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#55 0x000064bf4c096bbc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#56 0x000064bf4c08f994 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#57 0x000064bf4b29f1c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#58 0x000064bf4c0ef4bf in  () at /usr/lib/libQt6Widgets.so.6
#59 0x000064bf4c0ea525 in  () at /usr/lib/libQt6Widgets.so.6
#60 0x000064bf4c096bcc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#61 0x000064bf4b29f1c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#62 0x000064bf4b89565c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt6Gui.so.6
#63 0x000064bf4b8f3285 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Gui.so.6
#64 0x000064bf4bc7af75 in  () at /usr/lib/libQt6Gui.so.6
#65 0x000064bf4a4c181b in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#66 0x000064bf4a517ec9 in  () at /usr/lib/libglib-2.0.so.0
#67 0x000064bf4a4c00d2 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#68 0x000064bf4b4c1422 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#69 0x000064bf4b2a9b94 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#70 0x000064bf4b2a3a5b in QCoreApplication::exec() () at /usr/lib/libQt6Core.so.6
#71 0x0000001d0d198fe9 in  ()
#72 0x000064bf4a780290 in  () at /usr/lib/libc.so.6
#73 0x000064bf4a78034a in __libc_start_main () at /usr/lib/libc.so.6
#74 0x0000001d0d19b5a5 in  ()
```

**Comment by rncbc** [comment]
the sfizz should have been blacklisted (due to it segfault'ing the plugin scan out-of-process); any attempt to load it directly  though obviously crashes the whole show.

the problem is int the sfizz.so and not appearing in the stacktrace because it isn't compiled with debug info of course.

**Comment by rncbc** [comment]
otoh. sfizz VST3 is just working great here (openSUSE TW) : no crash on scan nor loading either

anyhow, what's the status on sfizz LV2 anyway?
